'use strict';

const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('screenlogic', {
  discover: (timeout) => invoke('screenlogic:discover', timeout),
  closeFinder: () => invoke('screenlogic:closeFinder'),
  remoteLogin: (systemName) => invoke('screenlogic:remoteLogin', systemName),
  closeRemoteLogin: () => invoke('screenlogic:closeRemoteLogin'),
  initUnit: (server) => invoke('screenlogic:initUnit', server),
  initConnection: (systemName, address, port, password, senderId) => invoke('screenlogic:initConnection', systemName, address, port, password, senderId),
  connect: () => invoke('screenlogic:connect'),
  close: () => invoke('screenlogic:close'),
  addClient: (clientId, senderId) => invoke('screenlogic:addClient', clientId, senderId),
  removeClient: (clientId, senderId) => invoke('screenlogic:removeClient', clientId, senderId),
  getVersion: (senderId) => invoke('screenlogic:getVersion', senderId),
  pingServer: (senderId) => invoke('screenlogic:pingServer', senderId),
  reconnect: () => invoke('screenlogic:reconnect'),
  status: () => invoke('screenlogic:status'),
  getSystemTime: (senderId) => invoke('screenlogic:getSystemTime', senderId),
  setSystemTime: (date, adjustForDST, senderId) => invoke('screenlogic:setSystemTime', date, adjustForDST, senderId),
  getWeatherForecast: (senderId) => invoke('screenlogic:getWeatherForecast', senderId),
  getHistoryData: (fromTime, toTime, senderId) => invoke('screenlogic:getHistoryData', fromTime, toTime, senderId),
  getAllCircuitNames: (senderId) => invoke('screenlogic:getAllCircuitNames', senderId),
  getNCircuitNames: (senderId) => invoke('screenlogic:getNCircuitNames', senderId),
  getCircuitNames: (size, senderId) => invoke('screenlogic:getCircuitNames', size, senderId),
  getCircuitDefinitions: (senderId) => invoke('screenlogic:getCircuitDefinitions', senderId),
  getEquipmentConfiguration: (senderId) => invoke('screenlogic:getEquipmentConfiguration', senderId),
  getEquipmentState: (senderId) => invoke('screenlogic:getEquipmentState', senderId),
  getCustomNames: (senderId) => invoke('screenlogic:getCustomNames', senderId),
  setCustomName: (idx, name, senderId) => invoke('screenlogic:setCustomName', idx, name, senderId),
  cancelDelay: (senderId) => invoke('screenlogic:cancelDelay', senderId),
  getControllerConfig: (senderId) => invoke('screenlogic:getControllerConfig', senderId),
  sendLightCommand: (command, senderId) => invoke('screenlogic:sendLightCommand', command, senderId),
  setCircuitRuntimeById: (circuitId, runTime, senderId) => invoke('screenlogic:setCircuitRuntimeById', circuitId, runTime, senderId),
  setCircuit: (circuitId, nameIndex, circuitFunction, circuitInterface, freeze, colorPos, senderId) => invoke('screenlogic:setCircuit', circuitId, nameIndex, circuitFunction, circuitInterface, freeze, colorPos, senderId),
  setCircuitState: (circuitId, state, senderId) => invoke('screenlogic:setCircuitState', circuitId, state, senderId),
  setSetPoint: (bodyIndex, temperature, senderId) => invoke('screenlogic:setSetPoint', bodyIndex, temperature, senderId),
  setCoolSetPoint: (bodyIndex, temperature, senderId) => invoke('screenlogic:setCoolSetPoint', bodyIndex, temperature, senderId),
  setHeatMode: (bodyIndex, heatMode, senderId) => invoke('screenlogic:setHeatMode', bodyIndex, heatMode, senderId),
  setPumpSpeed: (pumpId, circuitId, speed, isRPMs, senderId) => invoke('screenlogic:setPumpSpeed', pumpId, circuitId, speed, isRPMs, senderId),
  getPumpStatus: (pumpId, senderId) => invoke('screenlogic:getPumpStatus', pumpId, senderId),
  setScheduleEventById: (scheduleId, circuitId, startTime, stopTime, dayMask, flags, heatCmd, heatSetPoint, senderId) => invoke('screenlogic:setScheduleEventById', scheduleId, circuitId, startTime, stopTime, dayMask, flags, heatCmd, heatSetPoint, senderId),
  addNewScheduleEvent: (scheduleType, senderId) => invoke('screenlogic:addNewScheduleEvent', scheduleType, senderId),
  deleteScheduleEventById: (scheduleId, senderId) => invoke('screenlogic:deleteScheduleEventById', scheduleId, senderId),
  getScheduleData: (scheduleType, senderId) => invoke('screenlogic:getScheduleData', scheduleType, senderId),
  getChemHistoryData: (fromTime, toTime, senderId) => invoke('screenlogic:getChemHistoryData', fromTime, toTime, senderId),
  getChemicalData: (senderId) => invoke('screenlogic:getChemicalData', senderId),
  getIntellichlorConfig: (senderId) => invoke('screenlogic:getIntellichlorConfig', senderId),
  setIntellichlorOutput: (poolOutput, spaOutput, senderId) => invoke('screenlogic:setIntellichlorOutput', poolOutput, spaOutput, senderId),
  setIntellichlorIsActive: (isActive, senderId) => invoke('screenlogic:setIntellichlorIsActive', isActive, senderId),
});
